In [ ]:
# Leitura de arquivos CSV

import csv

arquivo = open('alunos.csv', 'r')

planilha = csv.reader(arquivo, delimiter=';', lineterminator='\n')

for linha in planilha:
    print(linha)

arquivo.close()

In [2]:
#### Bônus para o trabalho final

# Pandas
# https://medium.com/@henrique.gelatti/diferentes-formas-de-ler-um-arquivo-csv-utilizando-a-biblioteca-pandas-dbeab96555ba
# https://sparkbyexamples.com/pandas/pandas-filter-by-column-value/
# https://pandas.pydata.org/docs/reference/frame.html

import pandas as pd
dataframe = pd.read_csv('ds-py-estruturas-dados-II-desafio-final/sp_transporte.csv')

In [2]:
dataframe

     _estacaoId         _nome  _ordem  _linhaId  _linha  _tipoId  _tipo
0           152      Ana Rosa       1         1  1-Azul        1  Metrô
1            14       Armênia       1         1  1-Azul        1  Metrô
2            12     Carandiru       1         1  1-Azul        1  Metrô
3            29     Conceição       1         1  1-Azul        1  Metrô
4            30     Jabaquara       1         1  1-Azul        1  Metrô
..          ...           ...     ...       ...     ...      ...    ...
205         143   Piraporinha     999        11    EMTU        3   EMTU
206         180   Santo André     999        11    EMTU        3   EMTU
207         144  São Bernardo     999        11    EMTU        3   EMTU
208         147    São Mateus     999        11    EMTU        3   EMTU
209         146   Sônia Maria     999        11    EMTU        3   EMTU

[210 rows x 7 columns]

In [10]:
id_linha = 11
estacoes_emtu = dataframe.query(f'_linhaId == {1}')
estacoes_ordernadas = estacoes_emtu.sort_values(by=['_estacaoId'])
estacoes_ordernadas

,_estacaoId,_nome,_ordem,_linhaId,_linha,_tipoId,_tipo
20,8,Tucuruvi,1,1,1-Azul,1,Metrô
8,9,Parada Inglesa,1,1,1-Azul,1,Metrô
6,10,Jardim São Paulo-Ayrton Senna,1,1,1-Azul,1,Metrô
13,11,Santana,1,1,1-Azul,1,Metrô
2,12,Carandiru,1,1,1-Azul,1,Metrô
10,13,Portuguesa-Tietê,1,1,1-Azul,1,Metrô
1,14,Armênia,1,1,1-Azul,1,Metrô
19,15,Tiradentes,1,1,1-Azul,1,Metrô
14,17,São Bento,1,1,1-Azul,1,Metrô
5,19,Japão-Liberdade,1,1,1-Azul,1,Metrô
15,20,São Joaquim,1,1,1-Azul,1,Metrô
21,21,Vergueiro,1,1,1-Azul,1,Metrô
22,24,Vila Mariana,1,1,1-Azul,1,Metrô
12,25,SantaCruz,1,1,1-Azul,1,Metrô
11,26,Praça da Árvore,1,1,1-Azul,1,Metrô
17,27,Saúde,1,1,1-Azul,1,Metrô
16,28,São Judas,1,1,1-Azul,1,Metrô
3,29,Conceição,1,1,1-Azul,1,Metrô
4,30,Jabaquara,1,1,1-Azul,1,Metrô
0,152,Ana Rosa,1,1,1-Azul,1,Metrô
7,171,Luz,1,1,1-Azul,1,Metrô
9,174,Paraíso,1,1,1-Azul,1,Metrô
18,186,Sé,1,1,1-Azul,1,Metrô

In [4]:
value='1-Azul'
estacoes_azul = dataframe.query("_linha == @value")
estacoes_azul

,_estacaoId,_nome,_ordem,_linhaId,_linha,_tipoId,_tipo
0,152,Ana Rosa,1,1,1-Azul,1,Metrô
1,14,Armênia,1,1,1-Azul,1,Metrô
2,12,Carandiru,1,1,1-Azul,1,Metrô
3,29,Conceição,1,1,1-Azul,1,Metrô
4,30,Jabaquara,1,1,1-Azul,1,Metrô
5,19,Japão-Liberdade,1,1,1-Azul,1,Metrô
6,10,Jardim São Paulo-Ayrton Senna,1,1,1-Azul,1,Metrô
7,171,Luz,1,1,1-Azul,1,Metrô
8,9,Parada Inglesa,1,1,1-Azul,1,Metrô
9,174,Paraíso,1,1,1-Azul,1,Metrô
10,13,Portuguesa-Tietê,1,1,1-Azul,1,Metrô
11,26,Praça da Árvore,1,1,1-Azul,1,Metrô
12,25,SantaCruz,1,1,1-Azul,1,Metrô
13,11,Santana,1,1,1-Azul,1,Metrô
14,17,São Bento,1,1,1-Azul,1,Metrô
15,20,São Joaquim,1,1,1-Azul,1,Metrô
16,28,São Judas,1,1,1-Azul,1,Metrô
17,27,Saúde,1,1,1-Azul,1,Metrô
18,186,Sé,1,1,1-Azul,1,Metrô
19,15,Tiradentes,1,1,1-Azul,1,Metrô
20,8,Tucuruvi,1,1,1-Azul,1,Metrô
21,21,Vergueiro,1,1,1-Azul,1,Metrô
22,24,Vila Mariana,1,1,1-Azul,1,Metrô

In [5]:
# Mostrar somente os valores da coluna _estacaoId
dataframe['_estacaoId']

0      152
1       14
2       12
3       29
4       30
      ...
205    143
206    180
207    144
208    147
209    146
Name: _estacaoId, Length: 210, dtype: int64

# Grafos

Grafo é um par de conjuntos `G = (V, E)` onde:

    `V` é um conjunto de vértices (ou **nós**)
    `E` um conjunto de arestas. Cada aresta é um par de vértices.

*Nós* são os elementos que queremos modelar, e as arestas são as relações entre os ítens.

Em outras palavras, grafos são formas de visualizar relações entre elementos.

Exemplo de grafo:

<img src="https://algoritmosempython.com.br/images/algoritmos-python/algoritmos-grafos/ModelagemGrafosExemplo.png" width=400>

&nbsp;

Arestas podem ser unidirecionais (mão única) ou bidirecionais (mão dupla)

<img src="https://www.ime.usp.br/~pf/algoritmos_para_grafos/aulas/figs/Sedgewick-Wayne/TinyNetworkOnly.png" width=400>

&nbsp;

Arestas podem ter rótulos (também chamados de **peso** ou **custo**). Podem indicar, por exemplo, a distância entre dois pontos, o custo de percorrer o caminho, o grau de amizade em uma rede social, etc.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Prim_Algorithm_0.svg/250px-Prim_Algorithm_0.svg.png" width=400 style="background-color:white">

&nbsp;

Quando existe uma aresta conectando um vértice `u` à um vértice `v` (`u-v`), dizemos que `v` é vizinho de `u`.

Em grafos unidirecionais, é comum usarmos a nomenclatura de árvores e dizer que `u` é pai de `v` caso exista uma aresta direcionada `u -> v`

_________

## Como representar um grafo no computador?

Formas mais comuns:

- Matriz de adjacência
- Listas de adjacências

#### Matriz de adjacência

Para criar um grafo como uma matriz de adjacências, definimos uma matriz `M` de dimensões `n x n`, sendo `n` a quantidade de vértices.

Inicializamos a matriz com zeros, e "marcamos" `M[u][v]` com um valor diferente de zero caso exista uma aresta conectando o vértice `u` ao vértice `v`.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/1f5e0fd3-572c-479a-8a53-74d8212c5e5c.jpg" width=500>

No exemplo da figura acima vemos um grafo **não direcionado** e por isso temos a matriz **diagonalmente simétrica** (`M[u][v] == M[v][u]`). 

> Ou seja, a aresta `u-v` é "de mão dupla".

&nbsp;

C essa estrutura também é possivel modelar grafos direcionados, basta não impor a simetria.

Dica: a ponta da flecha é a linha (a ideia é que a flecha sai da linha e vai pra coluna)

<img src="https://algoritmosempython.com.br/images/algoritmos-python/algoritmos-grafos/GrafoMatrizAdjacencia.png" width=400>

Essa estrutura também permite representar arestas com peso, basta utilizar o valor do peso para marcar a aresta no lugar da constante 1 que utilizamos.

<img src="https://www.researchgate.net/profile/Paula-Gabrielly-Rodrigues/publication/326722760/figure/fig5/AS:654507780345864@1533058223380/Figura-4-7-Grafo-nao-ponderado-A-e-ponderado-B-com-suas-respectivas-matrizes-de.png" width=500>

#### Lista de adjacências

Para **grafos esparsos (grafos com poucas arestas)**, a matriz de adjacência tende a gerar um desperdício de espaço (armazenando um monte de zeros para as conexões que não existem no grafo).

Alternativamente, utiliza-se Listas de adjacências. Ajuda a não gastar espaço com arestas inexistentes.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/9775dad0-c900-42e9-87fa-41d78b73444c.jpg" width=500>

Mas e se o grafo tiver uma grande quantidade de arestas? Ainda estariamos economizando espaço?

_________

#### Comparação das estruturas (em termos de complexidade)

Para um grafo `G=(V,E)` composto de vértices `V` e arestas `E`, nas operações mais básicas.

|                            	| Matriz de Adj. 	| Lista de Adj.  	|
|----------------------------	|----------------	|----------------	|
| inserir aresta             	| O(1)           	| O(1)           	|
| remover aresta             	| O(1)           	| O(`grau_max(G)`) 	|
| verificar adj. de dois nós 	| O(1)           	| O(`grau_max(G)`) 	|
| listar vizinhos de um nó   	| O(`len(V)`)         	| O(`grau_max(G)`) 	|
| espaço de armazenamento    	| O(`len(V)^2`)      	| O(`len(V) + len(E)`)  |

Obs: O **grau** de um vértice, é a **quantidade de arestas que incide sobre esse vértice.** O grau máximo de um grafo `G` é o maior grau dentre todos os vértices de `G`.

Será que faz sentido dizer que uma representação é melhor que a outra?
Em que situações seria melhor usar a matriz? E a lista?

#### Pausa pra implementação

Implementem um grafo como matriz de adjacência

matriz = [][]

adicionar_arestas(linha, coluna, peso = 1, bidirecional = true)

verificar_vizinhos(nó)